       - name: Deploy WAR To Tomcat
        run: |
          ssh \
            -o StrictHostKeyChecking=no \
            -i ~/.ssh/key.pem \
            "$EC2_USER@${{ steps.ec2.outputs.public_ip }}" "
              set -e

              sudo /opt/tomcat/bin/shutdown.sh 2>/dev/null || true
              sleep 5

              sudo rm -rf \
                /opt/tomcat/webapps/$APP_NAME \
                /opt/tomcat/webapps/$APP_NAME.war

              sudo cp \
                /tmp/$APP_NAME.war \
                /opt/tomcat/webapps/$APP_NAME.war

              sudo /opt/tomcat/bin/startup.sh

              echo 'WAR deployed successfully.'
            "

          - name: Verify Application
            run: |
          APP_URL="http://${{ steps.ec2.outputs.public_ip }}:8080/$APP_NAME/"

          for i in {1..20}; do
            if curl -fL "$APP_URL"; then
              echo ""
              echo "Application is running successfully."
              echo "URL: $APP_URL"
              exit 0
            fi

            echo "Waiting for application..."
            sleep 10
          done

          echo "Application verification failed."
          exit 1

       - name: Application URL
        run: |
          echo "Application deployed successfully"
          echo "http://${{ steps.ec2.outputs.public_ip }}:8080/$APP_NAME/"
